### ISSUE TITLE
pip installation is broken

### ISSUE THREAD

**Issue by prudnitskiy** [adw0rd/marcus#27]
DistributionNotFound: No distributions at all found for scipio in /home/proj/virtualenv/ve-ppro/lib/python2.7/site-packages (from django-marcus)

**Comment by adw0rd** [comment]
Hi, Pasha! Several days ago I decided to stop supporting django-marcus.

Because to me it's no longer interesting. I'm currently in the process of re-writing my blog to [Pelican](http://docs.getpelican.com/en/3.5.0/index.html) + Disqus. I'm sorry!

About scipio: Sagalaev remove scipio from pypi... I did nothing, I'm just tired. You can find scipio and publish on PyPI, or change path in setup.py to original github repo

**Comment by prudnitskiy** [comment]
I'll check your solution when I can see it. The Marcus project isn't the best i've ever seen (but it's better than Wordpress, for example. And it was the best blog engine on python). Maybe I'll take the support of macrus if I have a time for it and you don't mind.

**Comment by grigorov** [comment]
I am ready to support this engine. If the authors do not mind.

**Comment by adw0rd** [comment]
@prudnitskiy @grigorov 

I do not mind, decide which one of you is ready to support marcus

**Comment by adw0rd** [comment]
@prudnitskiy good night! Please attempt to installation of django-marcus again. I fixed many of old bugs and released 0.6.3 version

**Comment by adw0rd** [comment]
I forgot to say, with the new pip you should install as follows:

    pip install --process-dependency-links django-marcus
